name: Metrics
on:
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Detailed report
        uses: lowlighter/metrics@latest
        with:
            filename: metrics/pagespeed.svg
            token: NOT_NEEDED
            base: ""
            plugin_pagespeed: yes
            plugin_pagespeed_detailed: yes
            plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
            plugin_pagespeed_url: https://www.rahulpr.dev     
